//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ModelFirst_onyuzevericekme_login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_ModelFirstEntities : DbContext
    {
        public MVC_ModelFirstEntities()
            : base("name=MVC_ModelFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    }
}
